### ISSUE TITLE
Dockerfile missing?

### ISSUE THREAD

**Issue by tblom** [erisyon/plaster#135]
There doesn't seem to be a Dockerfile for the first step of setup indicated by the README.md:

`docker build -t plaster:latest .` 

This command issued from the root of the pulled plaster repository fails with:

`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/thomas/erisyon/plaster/Dockerfile: no such file or directory`

**Comment by ossareh** [comment]
Hi there @tblom, yes - there is some scar tissue in the repo and there are commands in our internal repo that do the bootstrap until we can get around to remedying that.
